CREATE TABLE `user`
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT user_pk PRIMARY KEY (id)
);

CREATE TABLE label
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT label_pk PRIMARY KEY (id)
);

CREATE TABLE note
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title     VARCHAR(255) NOT NULL,
    status    VARCHAR(10)  NOT NULL,
    message   TEXT,
    parent_id BIGINT,
    CONSTRAINT note_pk PRIMARY KEY (id),
    CONSTRAINT note_note_fk FOREIGN KEY (parent_id) REFERENCES note (id)
);

CREATE TABLE note_user
(
    note_id BIGINT      NOT NULL,
    user_id BIGINT      NOT NULL,
    role    VARCHAR(10) NOT NULL,
    CONSTRAINT note_user_pk PRIMARY KEY (note_id, user_id),
    CONSTRAINT note_user_note_fk FOREIGN KEY (note_id) REFERENCES note (id),
    CONSTRAINT note_user_user_fk FOREIGN KEY (user_id) REFERENCES `user` (id)
);

CREATE TABLE note_label
(
    note_id  BIGINT NOT NULL,
    label_id BIGINT NOT NULL,
    CONSTRAINT note_label_pk PRIMARY KEY (note_id, label_id),
    CONSTRAINT note_label_note_fk FOREIGN KEY (note_id) REFERENCES note (id),
    CONSTRAINT note_label_label_fk FOREIGN KEY (label_id) REFERENCES label (id)
);
